import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css"
import Navbar from "@/components/menu/Navbar";
import Footer from "@/components/footer/Footer";
import ToastComponent from "@/components/toastcomponent";
import LoaderProvider from "@/components/logoloader/loaderprovider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="fr">
      <body>
        <LoaderProvider>
          <Navbar />
          {children}
          <Footer />
          <ToastComponent />
        </LoaderProvider>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossOrigin="anonymous"></script>

      </body>
    </html>
  );
}
